name: Build Arch ISO
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - name: Prepare dirs
        run: |
          mkdir -p .pkgcache work out

      - name: Cache pacman packages
        uses: actions/cache@v4
        with:
          path: .pkgcache
          key: pacman-cache-v1

      - name: Build ISO in privileged Arch container
        run: |
          docker run --privileged --rm \
            -v "${{ github.workspace }}:/repo" \
            -v "${{ github.workspace }}/.pkgcache:/var/cache/pacman/pkg" \
            -v "${{ github.workspace }}/work:/work" \
            -v "${{ github.workspace }}/out:/out" \
            archlinux:latest \
            bash -lc '
              set -euxo pipefail
              sed -i "s/^#ParallelDownloads.*/ParallelDownloads = 10/" /etc/pacman.conf || true
          
              # Ensure gnupg and keyring are ready before upgrades
              pacman -Sy --noconfirm gnupg archlinux-keyring
              pacman-key --init
              pacman-key --populate archlinux
          
              pacman -Syu --noconfirm archiso
              
              cd /repo
              mkarchiso -v -w /work -o /out .
            '

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-iso
          path: out/*.iso
          overwrite: 'true'